//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int id_nota { get; set; }
        public Nullable<decimal> nota_1 { get; set; }
        public Nullable<decimal> nota_2 { get; set; }
        public Nullable<decimal> nota_3 { get; set; }
        public Nullable<int> identificacion { get; set; }
        public Nullable<decimal> promedio { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
